In [1]:
import torch

In [2]:
# grid_confc 网格的配置

In [10]:
xbound=[-50.0, 50.0, 0.5]  # 限制x方向的范围并划分网格
ybound=[-50.0, 50.0, 0.5]  # 限制y方向的范围并划分网格
zbound=[-10.0, 10.0, 20.0]  # 限制z方向的范围并划分网格
dbound=[4.0, 45.0, 1.0]  # 限制深度方向的范围并划分网格

In [11]:
def gen_dx_bx(xbound, ybound, zbound):  # 划分网格
    dx = torch.Tensor([row[2] for row in [xbound, ybound, zbound]])  
    bx = torch.Tensor([row[0] + row[2]/2.0 for row in [xbound, ybound, zbound]])  
    nx = torch.LongTensor([(row[1] - row[0]) / row[2] for row in [xbound, ybound, zbound]])  
    return dx, bx, nx

In [13]:
dx, bx, nx = gen_dx_bx(xbound, ybound, zbound)

<ipython-input-11-ddedb1f19036>:6: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  nx = torch.LongTensor([(row[1] - row[0]) / row[2] for row in [xbound, ybound, zbound]])


In [14]:
# 分别为x, y, z三个方向上的网格间距
dx 

tensor([ 0.5000,  0.5000, 20.0000])

In [15]:
# 分别为x, y, z三个方向上第一个格子的坐标
bx

tensor([-49.7500, -49.7500,   0.0000])

In [16]:
# 分别为x, y, z三个方向上格子的数量
nx

tensor([200, 200,   1])

In [18]:
torch.arange(*dbound, dtype=torch.float).view(-1, 1, 1).expand(-1, 1, 1)

tensor([[[ 4.]],

        [[ 5.]],

        [[ 6.]],

        [[ 7.]],

        [[ 8.]],

        [[ 9.]],

        [[10.]],

        [[11.]],

        [[12.]],

        [[13.]],

        [[14.]],

        [[15.]],

        [[16.]],

        [[17.]],

        [[18.]],

        [[19.]],

        [[20.]],

        [[21.]],

        [[22.]],

        [[23.]],

        [[24.]],

        [[25.]],

        [[26.]],

        [[27.]],

        [[28.]],

        [[29.]],

        [[30.]],

        [[31.]],

        [[32.]],

        [[33.]],

        [[34.]],

        [[35.]],

        [[36.]],

        [[37.]],

        [[38.]],

        [[39.]],

        [[40.]],

        [[41.]],

        [[42.]],

        [[43.]],

        [[44.]]])

In [ ]:
# create_frustum 创建视锥

In [20]:
# 原始图片大小
ogfW = 352
ogfH = 128
# 下采样倍数为16
fH = 8
fW = 22
# D: 41 表示深度方向上网格的数量
D = 41  
# 在0到351上划分22个格子 xs: DxfHxfW(41x8x22)
xs = torch.linspace(0, ogfW - 1, fW, dtype=torch.float).view(1, 1, fW).expand(D, fH, fW)
# 在0到127上划分8个格子 ys: DxfHxfW(41x8x22)
ys = torch.linspace(0, ogfH - 1, fH, dtype=torch.float).view(1, fH, 1).expand(D, fH, fW)

In [23]:
xs[0]

tensor([[  0.0000,  16.7143,  33.4286,  50.1429,  66.8571,  83.5714, 100.2857,
         117.0000, 133.7143, 150.4286, 167.1429, 183.8571, 200.5714, 217.2857,
         234.0000, 250.7143, 267.4286, 284.1429, 300.8571, 317.5714, 334.2857,
         351.0000],
        [  0.0000,  16.7143,  33.4286,  50.1429,  66.8571,  83.5714, 100.2857,
         117.0000, 133.7143, 150.4286, 167.1429, 183.8571, 200.5714, 217.2857,
         234.0000, 250.7143, 267.4286, 284.1429, 300.8571, 317.5714, 334.2857,
         351.0000],
        [  0.0000,  16.7143,  33.4286,  50.1429,  66.8571,  83.5714, 100.2857,
         117.0000, 133.7143, 150.4286, 167.1429, 183.8571, 200.5714, 217.2857,
         234.0000, 250.7143, 267.4286, 284.1429, 300.8571, 317.5714, 334.2857,
         351.0000],
        [  0.0000,  16.7143,  33.4286,  50.1429,  66.8571,  83.5714, 100.2857,
         117.0000, 133.7143, 150.4286, 167.1429, 183.8571, 200.5714, 217.2857,
         234.0000, 250.7143, 267.4286, 284.1429, 300.8571, 317.5714, 33

In [24]:
ys[0]

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000],
        [ 18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,
          18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,
          18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,  18.1429,
          18.1429],
        [ 36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,
          36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,
          36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,  36.2857,
          36.2857],
        [ 54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  54.4286,
          54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  54.4286,
          54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  54.4286,  5

In [26]:
ds = torch.arange(*dbound, dtype=torch.float).view(-1, 1, 1).expand(-1, fH, fW)

In [27]:
ds

tensor([[[ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
         [ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
         [ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
         ...,
         [ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
         [ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
         [ 4.,  4.,  4.,  ...,  4.,  4.,  4.]],

        [[ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
         ...,
         [ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  ...,  5.,  5.,  5.]],

        [[ 6.,  6.,  6.,  ...,  6.,  6.,  6.],
         [ 6.,  6.,  6.,  ...,  6.,  6.,  6.],
         [ 6.,  6.,  6.,  ...,  6.,  6.,  6.],
         ...,
         [ 6.,  6.,  6.,  ...,  6.,  6.,  6.],
         [ 6.,  6.,  6.,  ...,  6.,  6.,  6.],
         [ 6.,  6.,  6.,  ...,  6.,  6.,  6.]],

        ...,

        [[42., 42., 42.,  ..., 42., 42., 42.],
         [42., 42., 42.,  ..., 42., 42., 42.]

In [28]:
frustum = torch.stack((xs, ys, ds), -1)

In [29]:
frustum
# D x H x W x 3 （41*8*22*3）

tensor([[[[  0.0000,   0.0000,   4.0000],
          [ 16.7143,   0.0000,   4.0000],
          [ 33.4286,   0.0000,   4.0000],
          ...,
          [317.5714,   0.0000,   4.0000],
          [334.2857,   0.0000,   4.0000],
          [351.0000,   0.0000,   4.0000]],

         [[  0.0000,  18.1429,   4.0000],
          [ 16.7143,  18.1429,   4.0000],
          [ 33.4286,  18.1429,   4.0000],
          ...,
          [317.5714,  18.1429,   4.0000],
          [334.2857,  18.1429,   4.0000],
          [351.0000,  18.1429,   4.0000]],

         [[  0.0000,  36.2857,   4.0000],
          [ 16.7143,  36.2857,   4.0000],
          [ 33.4286,  36.2857,   4.0000],
          ...,
          [317.5714,  36.2857,   4.0000],
          [334.2857,  36.2857,   4.0000],
          [351.0000,  36.2857,   4.0000]],

         ...,

         [[  0.0000,  90.7143,   4.0000],
          [ 16.7143,  90.7143,   4.0000],
          [ 33.4286,  90.7143,   4.0000],
          ...,
          [317.5714,  90.7143,   4.00